"use client";

import { useState, useTransition } from "react";
import { generateMonthlySummary } from "@/lib/actions/summary";

export default function SummaryGenerator() {
  const [pending, startTransition] = useTransition();
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [model, setModel] = useState<string | null>(null);

  function run() {
    setError(null);
    startTransition(async () => {
      const result = await generateMonthlySummary();
      if (result.ok) {
        setSummary(result.summary);
        setModel(result.model);
      } else {
        setError(result.error);
        setSummary(null);
      }
    });
  }

  return (
    <div>
      <button
        onClick={run}
        disabled={pending}
        className="rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-60"
      >
        {pending ? "Generating…" : summary ? "Regenerate summary" : "Generate summary"}
      </button>

      {error && (
        <p className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/40">
          {error}
        </p>
      )}

      {summary && (
        <div className="mt-6">
          {/* Plain-text rendering — preserve the model's paragraph/line breaks. */}
          <div className="whitespace-pre-wrap text-sm leading-relaxed">{summary}</div>
          {model && (
            <p className="mt-4 text-xs text-gray-400">Generated by {model}</p>
          )}
        </div>
      )}
    </div>
  );
}
